12-Consuming-REST-API/starter/mvc-app/Models/VehicleSettings.cs
namespace westcoast_cars.web.Models
{
    public class VehicleSettings
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

12-Consuming-REST-API/starter/mvc-app/ViewModels/VehicleDetailsViewModel.cs
namespace westcoast_cars.web.ViewModels
{
    public class VehicleDetailsViewModel : VehiclesListViewModel
    {
        public int Value { get; set; }
        public string Description { get; set; }
    }
}

12-Consuming-REST-API/starter/mvc-app/ViewModels/VehiclePostViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace westcoast_cars.web.ViewModels;

public class VehiclePostViewModel
{
    [Required(ErrorMessage = "Registreringsnummer är obligatoriskt")]
    [DisplayName("Registrerings nummer")]
    public string RegistrationNumber { get; set; } = "";

    public string Manufacturer { get; set; }

    [Required(ErrorMessage = "Modell är obligatoriskt")]
    [DisplayName("Modell benämning")]
    public string Model { get; set; } = "";

    [Required(ErrorMessage = "Modell år är obligatoriskt")]
    [DisplayName("Modell År")]
    public string ModelYear { get; set; } = "";

    public int Mileage { get; set; }

    public List<SelectListItem> Manufacturers { get; set; }

    public string FuelType { get; set; }

    public List<SelectListItem> FuelTypes { get; set; }

    public string Transmission { get; set; }

    public List<SelectListItem> Transmissions { get; set; }
}

12-Consuming-REST-API/starter/mvc-app/ViewModels/VehiclesListViewModel.cs
namespace westcoast_cars.web.ViewModels
{
    public class VehiclesListViewModel
    {
        public int Id { get; set; }
        public string RegistrationNumber { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string ModelYear { get; set; }
        public int Mileage { get; set; }
        public string FuelType { get; set; }
        public string TransmissionType { get; set; }
        public string ImageUrl { get; set; }
    }
}

12-Consuming-REST-API/starter/mvc-app/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace westcoast_cars.web.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View("Index");
    }
}

12-Consuming-REST-API/starter/mvc-app/Controllers/VehiclesController.cs
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using westcoast_cars.web.Models;
using westcoast_cars.web.ViewModels;
using static System.Net.Mime.MediaTypeNames;

namespace westcoast_cars.web.Controllers
{
    [Route("vehicles")]
    public class VehiclesController : Controller
    {
        public IActionResult Index()
        {


            return View("Index");
        }

        [HttpGet("details/{vehicleId}")]
        public IActionResult Details(int vehicleId)
        {
            return View("Details");
        }

        [HttpGet("create")]
        public IActionResult Create()
        {

            var vehicle = new VehiclePostViewModel();

            return View("Create", vehicle);

        }

        [HttpPost("create")]
        public IActionResult Create(VehiclePostViewModel vehicle)
        {
            if (!ModelState.IsValid) return View("Create", vehicle);

            var model = new
            {
                RegistrationNumber = vehicle.RegistrationNumber,
                Manufacturer = vehicle.Manufacturer,
                Model = vehicle.Model,
                ModelYear = vehicle.ModelYear,
                FuelType = vehicle.FuelType,
                TransmissionType = vehicle.Transmission,
                Mileage = vehicle.Mileage,
                Description = "Test"
            };

            return Content("Done!");
        }
    }
}

12-Consuming-REST-API/starter/mvc-app/Views/Home/Index.cshtml
@{
    ViewBag.PageTitle = "Välkommen till";
}

@section styles{
<link rel="stylesheet" href="~/css/landing-page.css" />
}

<div class="landing">
    <div class="content">
        <h1>Välkommen till Westcoast Cars</h1>
        <h2>Vi tillhandahåller begnade bilar</h2>
        <p>Med högsta kvalite all ifrån sportbilar till<br>
            familjebilar</p>

    </div>
</div>
<br>

@Html.ActionLink("Se våra bilar","Index", "Vehicles")

12-Consuming-REST-API/starter/mvc-app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://kit.fontawesome.com/55174c58a9.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/colors.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/utilities.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/navigation.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/gallery-page.css">
    <link rel="stylesheet" href="~/css/vehicle-detail-page.css">
    @RenderSection("styles", false)
    <link rel="stylesheet" href="~/css/styles.css">
    <title>@ViewBag.PageTitle - Westcoast Cars</title>
</head>

<body>
    <header>
        <nav class="navbar">
            <h1 class="logo"><span class="text-primary"><i class="fa-solid fa-car"></i>Westcoast </span>Cars</h1>
            <ul>
                <li><a asp-action="Index" asp-controller="Home">Start</a></li>
                <li><a asp-action="Index" asp-controller="Vehicles">Vehicles</a></li>
                <li><a asp-action="Create" asp-controller="Vehicles"><i class="fa-solid fa-plus"></i></a></li>
            </ul>
        </nav>
    </header>
    <main>
        @RenderBody()
    </main>

</body>

</html>

12-Consuming-REST-API/starter/mvc-app/Views/Shared/_WeeklyOffer.cshtml
<div class="alert">
    <div class="alert success">
        <h3>Veckans erbjudande!</h3>
        <h4>Vi skickar med rattmuff om ni bokar en bil denna vecka</h4>
    </div>
</div>

12-Consuming-REST-API/starter/mvc-app/Views/Vehicles/Create.cshtml
@model westcoast_cars.web.ViewModels.VehiclePostViewModel

<section class="page">
    <h1 class="page-title">Lägg till bil</h1>
    <div class="form-container">
        <form class="form" asp-action="create" method="post">
            <div class="form-control">
                <label asp-for="RegistrationNumber"></label>
                <input asp-for="RegistrationNumber" />
                <span class="error" asp-validation-for="RegistrationNumber"></span>
            </div>
            <div class="form-control">
                <label asp-for="Manufacturer"></label>
                <select asp-for="Manufacturer" asp-items="Model.Manufacturers"></select>
                <span class="error" asp-validation-for="Manufacturer"></span>
            </div>
            <div class="form-control">
                <label asp-for="Model"></label>
                <input asp-for="Model" />
                <span class="error" asp-validation-for="Model"></span>
            </div>
            <div class="form-control">
                <label asp-for="ModelYear"></label>
                <input asp-for="ModelYear" />
                <span class="error" asp-validation-for="ModelYear"></span>
            </div>
            <div class="form-control">
                <label asp-for="Mileage"></label>
                <input asp-for="Mileage" />
                <span class="error" asp-validation-for="Mileage"></span>
            </div>
            <div class="form-control">
                <label asp-for="Transmission"></label>
                <select asp-for="Transmission" asp-items="Model.Transmissions"></select>
                <span class="error" asp-validation-for="Transmission"></span>
            </div>
            <div class="form-control">
                <label asp-for="FuelType"></label>
                <select asp-for="FuelType" asp-items="Model.FuelTypes"></select>
                <span class="error" asp-validation-for="FuelType"></span>
            </div>
            <div class="form-control">
                <div class="buttons-container">
                    <button type="Submit" class="btn btn-dark"><i class="fa-sharp fa-solid fa-floppy-disk"></i>
                        Spara</button>
                    <a asp-action="index" asp-controller="VehiclesAdmin" class="btn btn-warning"><i
                            class="fa-solid fa-arrow-left"></i> Avbryt</a>
                </div>
            </div>
        </form>
    </div>
</section>

12-Consuming-REST-API/starter/mvc-app/Views/Vehicles/Details.cshtml
@model westcoast_cars.web.ViewModels.VehicleDetailsViewModel
@{
    ViewBag.PageTitle = "Information";
}

<article class="page">
    <section class="vehicle-detail-container">
        <div class="vehicle-detail">
            <span class="back-icon">
                <a asp-action="index"><span><i class="fa-regular fa-arrow-left-long"></i> Tillbaka</span></a>
            </span>
            <h2 class="vehicle-detail-header">@Model.Manufacturer - @Model.Model</h2>
            <img src="@Model.ImageUrl" alt="@Model.Model">
            <div class="vehicle-detail-info">
                <span><strong>Modell</strong></span>
                <span>@Model.Model</span>
                <span><strong>Årsmodell</strong></span>
                <span>@Model.ModelYear</span>
                <span><strong>Km</strong></span>
                <span>@Model.Mileage</span>
                <span><strong>Pris</strong></span>
                <span>@Model.Value</span>
            </div>
            <h4>Beskrivning</h4>
            <div>@Model.Description</div>
        </div>
    </section>
</article>

12-Consuming-REST-API/starter/mvc-app/Views/Vehicles/Index.cshtml
@model IEnumerable<westcoast_cars.web.ViewModels.VehiclesListViewModel>
@{
    ViewBag.PageTitle = "Våra bilar";
}

<article class="page">
    <h1 class="page-title">Våra bilar i lager</h1>

    <section class="gallery-wrapper">
        @foreach (var vehicle in Model)
        {
            <div class="gallery-card">
                <div>@vehicle.Manufacturer</div>
                <img src="@vehicle.ImageUrl" alt="@vehicle.Model">
                <div><span>@vehicle.Model</span>&nbsp;<span>@vehicle.ModelYear</span></div>
                <a class="btn btn-dark" asp-action="details" asp-route-vehicleId="@vehicle.Id">Se mer</a>
            </div>
        }
    </section>

</article>